# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/artful64"

  # Increase disk size
  config.disksize.size = '20GB'
  config.vm.provision :shell, :inline => "resize2fs /dev/sda1", :privileged => true

  # Install packages
  config.vm.provision :shell, :inline => "DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -yq bash-completion lxd lxd-client criu tmux", :privileged => true

  # Configure LXD
  config.vm.provision :shell, :inline => "lxd init --auto", :privileged => true

  ## Prefetch some container images for hands-on
  config.vm.provision :shell, :inline => "lxc image copy ubuntu:16.04 local: --copy-aliases", :privileged => true
  config.vm.provision :shell, :inline => "lxc image copy images:debian/stretch local: --copy-aliases", :privileged => true 

end
